# ===============================
# = DATA SOURCE
# ===============================
server :
  port : 8181

#spring:
#  main:
#    allow-bean-definition-overriding: true

#soap:
#  wsdl:
#    uri: http://localhost:8080/ws/thelibrary.wsdl
#    file: thelibrary.wsdl
#  ws:
#    target-name-space: http://thelibrary.org/ws
#    uri: http://localhost:8080/ws

client:
  ticketagent:
    address: http://localhost:8080

cxf:
  path: /thelibrary/ws
