<?xml version="1.0" encoding="UTF-8"?>

<definitions
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		targetNamespace="http://searchbook/"
		xmlns:tns="http://searchbook/"
		xmlns="http://schemas.xmlsoap.org/wsdl/"
		name="SearchBookService">

	<types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  targetNamespace="http://searchbook/">
			<xs:element name="getBookTitle" type="tns:getBookTitle"/>
			<xs:element name="getBookTitleResponse" type="tns:getBookTitleResponse"/>
			<xs:complexType name="getBookTitle">
				<xs:sequence>
					<xs:element name="arg0" type="xs:int" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="getBookTitleResponse">
				<xs:sequence>
					<xs:element name="return" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</types>

	<message name="getBookTitle">
		<part name="parameters" element="tns:getBookTitle"/>
	</message>

	<message name="getBookTitleResponse">
		<part name="parameters" element="tns:getBookTitleResponse"/>
	</message>

	<portType name="SearchBookService">
		<operation name="getBookTitle">
			<input message="tns:getBookTitle"/>
			<output message="tns:getBookTitleResponse"/>
		</operation>
	</portType>

	<binding name="SearchBookServicePortBinding" type="tns:SearchBookService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<operation name="getBookTitle">
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>

	<service name="getBookTitle">
		<port name="SearchBookServicePort" binding="tns:SearchBookServicePortBinding">
			<soap:address location="http://localhost:8080/SearchBookService/getBookTitle"/>
		</port>
	</service>

</definitions>
